apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: labels
spec:
  containers:
    - name: nginx
      image: nginx
      env:
      - name: COURSE
        value: "KUBERNETS"
      - name: TRAINER
        value: "Shiva"