apiVersion: v1
kind: ReplicaSet
metadata:
  name: roboshop
  labels:
    purpose: rs-demo
    project: roboshop
    app: nginx
spec:
  replica: 3
  selectors:
    matchlabels:
      purpose: rs-demo
      project: roboshop
      app: nginx
  templates:
    metadata:
      labels:
        purpose: rs-demo
        project: roboshop
        app: nginx
      spec:
        containers:
        - name: nginx
          image: nginx


